monitor=,1920x1080,auto,1

exec-once = waybar
#exec-once = swww init

input {
  kb_layout = us
  follow_mouse = 1
}

env = XCURSOR_SIZE,24

general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(33ccffee)
  col.inactive_border = rgba(595959aa)
}

bind = SUPER, Return, exec, foot
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, V, togglefloating
bind = SUPER, SPACE, exec, rofi -show drun
